### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by niraviry** [Hurleyking/AI_Smart_PI_Doorbell#2]
Hi. I see I am the 1st to post up question.
The installation is almost OK. It has some errors like extra spaces in some paths but this is easy to fix. 
Also the checkwifi.sh was not defined OK as the source is in the Door_Bell directory.
The real issue are:
Issue 1:
Handling the "other machine" (http etc.). Can I use my home-assistant RPi? I guess the change in the reffers to the auto auto_healing.py and doorbell_pi_start.py. 
BTW, you did not point to the location of these files (I have found them).
Issue 2:
How do you start the machine? I think it does not run from boot.
Issue 3:
There is a need for better explanation to the face recognition, especially the script issue.
Issue 4:
How do load reference faces?
Issue 5:
How do you link it to HA? Some examples will be appreciated.

**Comment by niraviry** [comment]
Although you did not answer it looks like the gTTS is not loaded due to the fact that it is not supporting Python 2.7.

**Comment by niraviry** [comment]
There are more errors.

**Comment by Hurleyking** [comment]
sorry only see now. I have lot of work becouse covid-19.  Tomorrow i will response all your questions

**Comment by Hurleyking** [comment]
Issue 1:
> Handling the "other machine" (http etc.). Can I use my home-assistant RPi? I guess the change in the reffers to the auto auto_healing.py and doorbell_pi_start.py.
> BTW, you did not point to the location of these files (I have found them).

**Yes, in auto_healing.py you need change variable http_server, http_password, http_user. So only need appoint to your server HTTP with basic AUTH.** 
```
`#Variables
http_server = '192.168.1.84:8008' #insert where your server HTTP

http_password = 'hurley' #insert where  you password for basic Auth

http_user = 'hurley'` #insert where  you username for basic Auth

```

Issue 2:

> How do you start the machine? I think it does not run from boot.

**It start on boot becouse you add in crontab:** 
`*/5 * * * * /usr/bin/sudo -H /usr/local/bin/checkwifi.sh >> /dev/null 2>&1
*/10 * * * * python /home/pi/AI_Smart_PI_Doorbell/doorbell_pi/auto_healing.py`

**Note: Check localation of files, note checkwifi.sh i copy to path /usr/local/bin/**


Issue 3:

> There is a need for better explanation to the face recognition, especially the script issue.

**You need firts created one group so in firts run you discomment line 348 after start you kill the program and comment again, this will create new group after this only needd add person.**

Issue 4:
`How do load reference faces?`

When scrip is running, you push button the photo go to path "/var/www/html/last_ring.jpg", for example push button for ring front of you, after that you photo go to  "/var/www/html/last_ring.jpg", now you publish to your mqtt "doorbell/live" with payload 
 {"new_person":"True","name":"niraviry"} . This publish will load you face. 

Issue 5:

> How do you link it to HA? Some examples will be appreciated.

**I link by mqtt  only becouse all action you can call by publish mqtt or read state using that:**

 ```
 - platform: mqtt
    name: Temperatura_doorbell
    state_topic: "Doorbell/Temperature"
    qos: 0
    unit_of_measurement: "ºC"

  - platform: mqtt
    name: Doorbell_rssi
    state_topic: "Doorbell/rssi"
    qos: 0
    unit_of_measurement: "dBm"
```


**Any questions?**

**Comment by niraviry** [comment]
Hi.

Thanks.

I will look into your answers and see if I have other questions.



‫בתאריך יום ו׳, 3 באפר׳ 2020 ב-1:26 מאת ‪Hurleyking‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Hurleyking** [comment]
Close
